/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostRouteImport } from './routes/post'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as BayHandleRouteImport } from './routes/bay.$handle'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as NigeriaIndexRouteImport } from './routes/nigeria.index'
import { Route as ApiPublicSmsInboundRouteImport } from './routes/api/public/sms-inbound'
import { Route as NigeriaStateIndexRouteImport } from './routes/nigeria.$state.index'
import { Route as NigeriaStatePlaceRouteImport } from './routes/nigeria.$state.$place'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const BayHandleRoute = BayHandleRouteImport.update({
  id: '/bay/$handle',
  path: '/bay/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NigeriaIndexRoute = NigeriaIndexRouteImport.update({
  id: '/nigeria/',
  path: '/nigeria/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsInboundRoute = ApiPublicSmsInboundRouteImport.update({
  id: '/api/public/sms-inbound',
  path: '/api/public/sms-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const NigeriaStateIndexRoute = NigeriaStateIndexRouteImport.update({
  id: '/nigeria/$state/',
  path: '/nigeria/$state/',
  getParentRoute: () => rootRouteImport,
} as any)
const NigeriaStatePlaceRoute = NigeriaStatePlaceRouteImport.update({
  id: '/nigeria/$state/$place',
  path: '/nigeria/$state/$place',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post': typeof PostRoute
  '/rules': typeof RulesRoute
  '/bay/$handle': typeof BayHandleRoute
  '/item/$id': typeof ItemIdRoute
  '/nigeria/': typeof NigeriaIndexRoute
  '/api/public/sms-inbound': typeof ApiPublicSmsInboundRoute
  '/nigeria/$state/$place': typeof NigeriaStatePlaceRoute
  '/nigeria/$state/': typeof NigeriaStateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post': typeof PostRoute
  '/rules': typeof RulesRoute
  '/bay/$handle': typeof BayHandleRoute
  '/item/$id': typeof ItemIdRoute
  '/nigeria': typeof NigeriaIndexRoute
  '/api/public/sms-inbound': typeof ApiPublicSmsInboundRoute
  '/nigeria/$state/$place': typeof NigeriaStatePlaceRoute
  '/nigeria/$state': typeof NigeriaStateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post': typeof PostRoute
  '/rules': typeof RulesRoute
  '/bay/$handle': typeof BayHandleRoute
  '/item/$id': typeof ItemIdRoute
  '/nigeria/': typeof NigeriaIndexRoute
  '/api/public/sms-inbound': typeof ApiPublicSmsInboundRoute
  '/nigeria/$state/$place': typeof NigeriaStatePlaceRoute
  '/nigeria/$state/': typeof NigeriaStateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post'
    | '/rules'
    | '/bay/$handle'
    | '/item/$id'
    | '/nigeria/'
    | '/api/public/sms-inbound'
    | '/nigeria/$state/$place'
    | '/nigeria/$state/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/post'
    | '/rules'
    | '/bay/$handle'
    | '/item/$id'
    | '/nigeria'
    | '/api/public/sms-inbound'
    | '/nigeria/$state/$place'
    | '/nigeria/$state'
  id:
    | '__root__'
    | '/'
    | '/post'
    | '/rules'
    | '/bay/$handle'
    | '/item/$id'
    | '/nigeria/'
    | '/api/public/sms-inbound'
    | '/nigeria/$state/$place'
    | '/nigeria/$state/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostRoute: typeof PostRoute
  RulesRoute: typeof RulesRoute
  BayHandleRoute: typeof BayHandleRoute
  ItemIdRoute: typeof ItemIdRoute
  NigeriaIndexRoute: typeof NigeriaIndexRoute
  ApiPublicSmsInboundRoute: typeof ApiPublicSmsInboundRoute
  NigeriaStatePlaceRoute: typeof NigeriaStatePlaceRoute
  NigeriaStateIndexRoute: typeof NigeriaStateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bay/$handle': {
      id: '/bay/$handle'
      path: '/bay/$handle'
      fullPath: '/bay/$handle'
      preLoaderRoute: typeof BayHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nigeria/': {
      id: '/nigeria/'
      path: '/nigeria'
      fullPath: '/nigeria/'
      preLoaderRoute: typeof NigeriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-inbound': {
      id: '/api/public/sms-inbound'
      path: '/api/public/sms-inbound'
      fullPath: '/api/public/sms-inbound'
      preLoaderRoute: typeof ApiPublicSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nigeria/$state/': {
      id: '/nigeria/$state/'
      path: '/nigeria/$state'
      fullPath: '/nigeria/$state/'
      preLoaderRoute: typeof NigeriaStateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nigeria/$state/$place': {
      id: '/nigeria/$state/$place'
      path: '/nigeria/$state/$place'
      fullPath: '/nigeria/$state/$place'
      preLoaderRoute: typeof NigeriaStatePlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostRoute: PostRoute,
  RulesRoute: RulesRoute,
  BayHandleRoute: BayHandleRoute,
  ItemIdRoute: ItemIdRoute,
  NigeriaIndexRoute: NigeriaIndexRoute,
  ApiPublicSmsInboundRoute: ApiPublicSmsInboundRoute,
  NigeriaStatePlaceRoute: NigeriaStatePlaceRoute,
  NigeriaStateIndexRoute: NigeriaStateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
